### PR TITLE
Resolves issue #9

### LINKED ISSUE #9: Improve CSRF token generating approach
As title, the current CSRF token generating approach is as follows:

- Set salt and default is empty string.
- Set session id.
- Using the `hash` to do `sha-256` to generate hashed value .

I think we can consider using the `random_int` or `random_bytes` to generate default salt value and make CSRF token secure.

And the improved approach is as follows:

- Set salt with `random_int` or `random_bytes` as a default value.
  - And it can also refer [Str::random](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Str.php#L428) to know how to generate a cryptographically secure random string.
- Set session id.
- Using the `hash` to do `sha-256` to generate hashed value.

Once this issue is accepted, I will be happy to work on this :).

### PR DESCRIPTION
**Pull request by peter279k**
Closes #9.

### CODE REVIEW

**Comment by odan** [comment]
The salt is optional and the constructor should contain only the minimum of the required parameters (clean code). If somebody wants to set the salt or other additional and optional parameters then it's possible to call the specific methods. I don't see much benefit by adding this optional parameter.

**Comment by peter279k** [comment]
Agree. But I think we need to figure out some ways to initial salt value rather than the empty salt value by default :).

**Comment by peter279k** [comment]
I think we can consider improving `getToken` method to remove optional `$salt` parameter from constructor:

```PHP
.......
 /**
     * Get CSRF token.
     *
     * @return string The token
     */
    public function getToken(): string
    {
        if (!empty($this->token)) {
            return $this->token;
        }

        $this->salt === '' ?: $this->salt = random_bytes(16);        

        return hash('sha256', $this->sessionId . $this->salt);
    }
.......
```

**Comment by odan** [comment]
This approach would lead to a different result if someone did not define the salt.

I would suggest defining the salt as a **required** parameter to make it more secure by default. 
Then we need to add it to the constructor and validate that it is not empty.

**Comment by peter279k** [comment]
Agree.

Do you have any suggestions about  request changes?

**Comment by peter279k** [comment]
I think it will be fine to let $salt variable to be required parameter on constructor method.

**Comment by odan** [comment]
I also would like to make the CsrfMiddleware more container "friendly" because the session should not be already startet within the container definiton. So we should remove the $sessionId from the constructor and add `$salt` parameter as required parameter to the constructor.

The new constructor for the IoC container:

```php
public function __construct(StreamFactoryInterface $streamFactory, string $salt)
{
        $this->streamFactory = $streamFactory;
        $this->setSalt($salt);
}
```

**Comment by peter279k** [comment]
@odan, I update PR and please review that.

If having any suggestion/request changes, please feel free to write comments :).

**Comment by odan** [comment]
I think this is better now :-) Thank you 👍

**Pull request merged**
